### ISSUE TITLE
Log showing debug log - DATABASE CURRENT SET ALLOW_SNAPSHOT_ISOLATION ON

### ISSUE THREAD

**Issue by PrasannaGrandhi** [rebus-org/FleetManager#106]
Suddenly fleet manager stopped working, getting below log and after that its not going further...
Any suggestions please...
`2021-08-06 06:01:09.934 +00:00|INF|||FleetManager.Model.Tech.SqlServer.Extensions.SqlServerExtensions|Initializing HybriDB document store...
2021-08-06 06:01:10.872 +00:00|DBG|||HybridDB|ALTER DATABASE CURRENT SET ALLOW_SNAPSHOT_ISOLATION ON;`

**Comment by PrasannaGrandhi** [comment]
Also, one more observation, I can't see Azure Servicebus error messages under failed messages. 

I could see the count in Active Overview for exceptions and errors as well but failed messages section is just empty. Am I misunderstanding the concept of failed messaged or did we missed something ?

**Comment by mookid8000** [comment]
Seems to be caused by HybridDB requiring enough privileges in SQL Server to change the schema.

SOLUTION: Either run Fleet Manager with enough privileges to do that, or – when this happens – start it up once with enough privileges, and then stop it again after the schema has been updated.

The problem only arises when the schema needs to be changed. so the issue will only happen in connection with updating Fleet Manager or running it for the first time.
