### ISSUE TITLE
Fleet Manager scaling question

### ISSUE THREAD

**Issue by ghost** [rebus-org/FleetManager#99]
I am planning how to install Fleet Manager in our Azure cloud.  Our system processes about 1 to 2 million messages in one day, these take approximately 2GB to 4GB of storage.  I have a few questions about scaling:

1. Would using SQL Azure be suitable for our needs, or do we need to think about higher performance?
2. For Fleet Manager's Azure ServiceBus, can we use the same ASB instance that we use for our queues?
3. Can we use VM scale sets to auto scale our Fleet Manager VMs?
4. How much file system storage do we need to have and how will this grow?

Thanks 🚀

**Comment by mookid8000** [comment]
> Would using SQL Azure be suitable for our needs, or do we need to think about higher performance?

I think so, yes. Not sure which tier though, but the requirements should be that high as SQL Server is only used for master data and alerts.

> For Fleet Manager's Azure ServiceBus, can we use the same ASB instance that we use for our queues?

Yes. Since you're running on a VM, you can also configure Fleet Manager to use the file system.

> Can we use VM scale sets to auto scale our Fleet Manager VMs?

No. FM must not and cannot run concurrently with itself right now, because it has a bunch of in-mem projections. Once these in-mem projections have been replaced with a distributed in-mem cache (Redis, memcached, ...) it should be possible to run multiple instances.

> How much file system storage do we need to have and how will this grow?

It's a little bit hard to predict, because it depends on how you use FM. The different projections that store their data in the file system will periodically clean things up, but they will not e.g. remove failed messages that are active. But if you have a fairly sensible approach to archiving your failed messages 🙂 then the disk storage used should not grow beyond some kind of upper limit.

If I was installing Fleet Manager on a VM, I'd provision a separate disk (e.g. a 1000 GB Premium SSD) and keep all the data on that.

**Comment by ghost** [comment]
Thanks, @mookid8000.  One last question: 

As we need to run a single FM instance, is it safe to have a little downtime in the FM instance while it scales?  That is, messages will continue to be received and will be processed after the FM instance starts up again?

**Comment by mookid8000** [comment]
Yes, that's completely safe. If it's down for a long time, then your Rebus instances might start complaining a bit, as they can no longer send data to FM, but a few minutes downtime is fine. 🙂

**Comment by ghost** [comment]
Thanks Mogens.  I thought as much, but best to check! :)
